# Generated by Django 3.2 on 2021-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoModel',
            fields=[
                ('alumnoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('alumnoNombre', models.CharField(db_column='nombre', max_length=50, null=True)),
                ('alumnoApellidoPaterno', models.CharField(db_column='apellido paterno', max_length=60, null=True)),
                ('alumnoApellidoMaterno', models.CharField(db_column='apellido materno', max_length=60, null=True)),
                ('alumnoEdad', models.IntegerField(db_column='edad')),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
    ]
